### ISSUE TITLE
パネル状態を１桁以上表示してほしい

### ISSUE THREAD

**Issue by taisirou** [GraphTechKEN/SerialOutputEx#1]
メトロ総合プラグイン等ではパネル状態に１桁以上の値が出力されており、修正をお願いできればと思います。
http://www.nozomi.vc/71_ats/metro/train.htm
SerialOutput.xmlにおいて` <Digit>3</Digit> `で指定できます。
（標準ではパネル状態は`<Digit>1</Digit> ` はグレーアウトしています）
当方で試したコードは以下になります。

```
case 13://パネル状態
 // str = Right(ats.PanelArray[_data.PanelNum].ToString(), _data.Digit);
str = Right(string.Format(format, (int)((ats.PanelArray[_data.PanelNum]))), _data.Digit);
```

検証内容
![スクリーンショット 2024-03-26](https://github.com/GraphTechKEN/SerialOutputEx/assets/32972270/eed63060-2048-4ea7-ba1f-45631f1bc75a)

**Comment by GraphTechKEN** [comment]
ご指摘ありがとうございます。エディタの方が桁数に対応していないかと思いますので、一旦検証いただいた内容で本体側を修正してみます。

**Comment by GraphTechKEN** [comment]
ご指摘ありがとうございます。エディタの方が桁数に対応していないかと思いますので、一旦検証いただいた内容で本体側を修正してみます。

**Comment by taisirou** [comment]
ありがとうございます。

**Comment by GraphTechKEN** [comment]
一度v0.7本体側をリリースいたします。もし不具合等がありましたら恐れ入りますがご報告いただけますと幸いです。
https://github.com/GraphTechKEN/SerialOutputEx/releases/tag/v0.7.40326.1
